name: cell-health
channels:
- conda-forge
dependencies:
- conda-forge::python=3.7.1
- conda-forge::pandas=0.24.2
- conda-forge::xlrd=1.2.0
- conda-forge::numpy=1.16.2
- conda-forge::requests=2.22.0
- conda-forge::scikit-learn=0.20.3
- conda-forge::dask-ml=1.0.0
- conda-forge::umap-learn=0.3.8
- conda-forge::joblib=0.13.2
- conda-forge::matplotlib=3.0.3
- conda-forge::seaborn=0.9.0
- conda-forge::plotnine=0.5.1
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=5.1.0
- conda-forge::nb_conda_kernels=2.2.1
- conda-forge::rpy2=2.9.4
- conda-forge::simplegeneric=0.8.1
- conda-forge::pip=19.2.2
- conda-forge::r-base=3.5.1
- conda-forge::r-stringr=1.3.1
- conda-forge::r-dplyr=0.8.0
- conda-forge::r-tidyr=0.8.1
- conda-forge::r-magrittr=1.5
- conda-forge::r-tibble=2.1.1
- conda-forge::r-docopt=0.6
- conda-forge::r-purrr=0.2.5
- conda-forge::r-readr=1.1.1
- conda-forge::r-readxl=1.1.0
- conda-forge::r-ggplot2=3.0.0
- conda-forge::r-cowplot=0.9.3
- conda-forge::r-ggrepel=0.8.0
- conda-forge::r-gridextra=2.3
- conda-forge::r-svglite=1.2.1
- conda-forge::r-irkernel=1.0.1
- conda-forge::r-optparse=1.6.0
- conda-forge::r-platetools=0.1.2
- conda-forge::r-curl=3.2
- conda-forge::r-futile.logger=1.4.3
- conda-forge::r-knitr=1.20
- pip:
  - git+https://github.com/cytomining/pycytominer@b915ea91414ed0722d4b4c64ff60d9015cf09255
